const SEARCH_FOCUSED = 'header/SEARCH_FOCUSED';
const SEARCH_UNFOCUS = 'header/SEARCH_UNFOCUS';
const SHOW_MESSAGE = 'header/SHOW_MESSAGE';
const CLOSE_MESSAGE = 'header/CLOSE_MESSAGE';
const SHOW_NOTIFICATIONS = 'header/SHOW_NOTIFICATIONS';
const CLOSE_NOTIFICATIONS = 'header/CLOSE_NOTIFICATIONS';
const SHOW_TASKS = 'header/SHOW_TASKS';
const CLOSE_TASKS = 'header/CLOSE_TASKS';
const SHOW_APPS = 'header/SHOW_APPS';
const CLOSE_APPS = 'header/CLOSE_APPS';
const SHOW_MORE = 'header/SHOW_MORE';
const CLOSE_MORE = 'header/CLOSE_MORE';
const FETCH_NOTIFICATION = 'header/FETCH_NOTIFICATION';
const FETCH_MESSAGE = 'header/FETCH_MESSAGE';
const FETCH_TASK = 'header/FETCH_TASK';

export { 
    SEARCH_FOCUSED, SEARCH_UNFOCUS, 
    SHOW_MESSAGE, CLOSE_MESSAGE, 
    SHOW_NOTIFICATIONS, CLOSE_NOTIFICATIONS, 
    SHOW_TASKS, CLOSE_TASKS,
    SHOW_APPS, CLOSE_APPS,
    SHOW_MORE, CLOSE_MORE,
    FETCH_NOTIFICATION, FETCH_MESSAGE, FETCH_TASK
};